name: CI

on: [push]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [stable, beta, nightly]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5
      - run: rustup update ${{ matrix.toolchain }}
      - run: cargo check --all-features --all

  nostd:
    name: Check no_std
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [stable, beta, nightly]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5
      - run: rustup update ${{ matrix.toolchain }}
      - run: cargo check --no-default-features --features=serde --all

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [stable, beta, nightly]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5
      - run: rustup update ${{ matrix.toolchain }}
      - run: cargo test --all-features --all

  miri:
    name: Miri
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [nightly]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5
      - run: rustup update ${{ matrix.toolchain }}
      - run: cargo +nightly miri test --all-features --all

  lints:
    name: Lints
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [stable, beta, nightly]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5
      - run: rustup update ${{ matrix.toolchain }}
      - run: cargo fmt --all -- --check
      - run: cargo clippy --all-features --all -- -D warnings
